language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("FilePaths"); Pkg.test("FilePaths"; coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.0
#       os: linux
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip
