name = "FilePaths"
uuid = "8fc22ac5-c921-52a6-82fd-178b2807b824"
authors = ["Rory Finnegan"]
version = "0.8.0"

[deps]
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
URIParser = "30578b45-9adc-5946-b283-645ec420af67"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
